# 应用配置
app:
  title: "GoInsight" # 网站Title
  listen_address: "127.0.0.1:8202" # 应用监听地址
  environment: "dev" # 环境设置，可选值为dev/prod
  secret_key: "m3cfrcrlbikc16h+u8c4!gru$h8@4k)@m^p4$f=pwqi1o$r_c^" # 应用密钥(JWT)，建议更改

crontab:
  sync_db_metas: "*/5 * * * *" # 每5分钟同步一次远程数据库库表元数据到本地数据库

database:
  driver: "mysql" # 数据库驱动
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  database: "gin_system"
  charset: "utf8mb4" # 数据库字符集
  max_idle_conns: 64 # 最大空闲连接数
  max_open_conns: 64 # 最大打开连接数
  conn_max_life_time: 3600 # 连接的最大存活时间
  conn_max_idle_time: 3600 # 连接的最大空闲时间


# 日志配置
log:
  level: "info" # 日志级别
  root_dir: "./logs" # 日志根目录

# nextcloud sso 配置
nextcloud:
  client_id: "tCiNuCV1cpdf5qiGLWQghf72dBekbhwpIFO4Kx9vx04s5q6OouWEeeogo59R7QhT"
  client_secret: "zdWPsaP5hiojf7LMaokY0VkzU9NgDTJhyEtQzUl1IWAmd7Ghjk3AY6HywOBI7glI"
  grant_type: "authorization_code"
  redirect_uri: "http://127.0.0.1:8202/user/sso/callback"
  token_url: "http://127.0.0.1:8181/apps/oauth2/api/v1/token"
  user_info_url: "http://127.0.0.1:8181/ocs/v2.php/cloud/user?format=json"
